# Generated by Django 2.0.2 on 2018-02-13 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_auto_20180209_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='mailing_list',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
