# Generated by Django 2.0.2 on 2018-02-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_announcement_send_it'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='send_it',
            new_name='send_mail_too',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='mailing_list',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
